INSERT INTO walk_route (id, name, distance_metres)
VALUES
    (1, 'Alyth Den', 5200),
    (2, 'Kinpurney Hill', 7800),
    (3, 'Tarbat Ness', 10000);

INSERT INTO walk (id, walk_date, walk_route_id)
VALUES
    (1, '2026/01/01', 1),
    (2, '2026/01/01', 2),
    (3, '2026/09/07', 3);

INSERT INTO munro (id, name, region, altitude_metres)
VALUES
    (1, 'Ben Nevis', 'Fort William to Loch Ericht', 1344),
    (2, 'Ben Macdui [Beinn Macduibh]', 'The Cairngorms', 1309),
    (3, 'Braeriach', 'The Cairngorms', 1296),
    (4, 'Cairn Toul', 'The Cairngorms', 1291),
    (5, 'Sgor an Lochain Uaine', 'The Cairngorms', 1258),
    (6, 'Cairn Gorm', 'The Cairngorms', 1245),
    (7, 'Aonach Beag', 'Fort William to Loch Ericht', 1234),
    (8, 'Aonach Mor', 'Fort William to Loch Ericht', 1221),
    (9, 'Carn Mor Dearg', 'Fort William to Loch Ericht', 1220),
    (10, 'Ben Lawers', 'Loch Rannoch to Loch Tay', 1214),
    (11, 'Beinn a Bhuird [Beinn a ''Bhuird North Top]', 'The Cairngorms', 1197),
    (12, 'Carn Eige [Carn Eighe]', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1183),
    (13, 'Beinn Mheadhoin', 'The Cairngorms', 1182),
    (14, 'Mam Sodhail', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1181),
    (15, 'Stob Choire Claurigh', 'Fort William to Loch Ericht', 1177),
    (16, 'Ben More', 'Firth of Clyde to Strathtay', 1174),
    (17, 'Ben Avon - Leabaidh an Daimh Bhuidhe', 'The Cairngorms', 1171),
    (18, 'Stob Binnein', 'Firth of Clyde to Strathtay', 1165),
    (19, 'Beinn Bhrotain', 'The Cairngorms', 1157),
    (20, 'Lochnagar - Cac Carn Beag', 'Braemar to Montrose', 1155),
    (21, 'Derry Cairngorm', 'The Cairngorms', 1155),
    (22, 'Sgurr nan Ceathreamhnan [Sgurr nan Ceathramhnan]', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1151),
    (23, 'Sgurr na Lapaich', 'Kyle of Lochalsh to Inverness, North of Loch Mullardoch', 1150),
    (24, 'Bidean nam Bian', 'Loch Leven to Connel Bridge and Glen Lochy', 1150),
    (25, 'Ben Alder', 'Fort William to Loch Ericht', 1148),
    (26, 'Geal-charn', 'Fort William to Loch Ericht', 1132),
    (27, 'An Riabhachan', 'Kyle of Lochalsh to Inverness, North of Loch Mullardoch', 1130),
    (28, 'Binnein Mor', 'Fort William to Loch Ericht', 1130),
    (29, 'Ben Lui [Beinn Laoigh]', 'Firth of Clyde to Strathtay', 1130),
    (30, 'Creag Meagaidh', 'Spean Bridge to Elgin', 1129),
    (31, 'Beinn a''Ghlo - Carn nan Gabhar', 'Forest of Atholl to Braemar and Blairgowrie', 1129),
    (32, 'Ben Cruachan', 'Loch Leven to Connel Bridge and Glen Lochy', 1126),
    (33, 'A''Chraileag [A''Chralaig]', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1120),
    (34, 'Aonach Beag', 'Fort William to Loch Ericht', 1118),
    (35, 'Sgor Gaoith', 'The Cairngorms', 1118),
    (36, 'Meall Garbh', 'Loch Rannoch to Loch Tay', 1118),
    (37, 'An Stuc', 'Loch Rannoch to Loch Tay', 1118),
    (38, 'Stob Coire Easain', 'Fort William to Loch Ericht', 1116),
    (39, 'Stob Coire an Laoigh', 'Fort William to Loch Ericht', 1116),
    (40, 'Monadh Mor', 'The Cairngorms', 1115),
    (41, 'Tom a''Choinich', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1113),
    (42, 'Sgurr Mor', 'Loch Maree to Loch Broom and Garve', 1112),
    (43, 'Carn a''Choire Bhoidheach', 'Braemar to Montrose', 1110),
    (44, 'Sgurr nan Conbhairean', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1109),
    (45, 'Meall a''Bhuiridh', 'Loch Leven to Connel Bridge and Glen Lochy', 1108),
    (46, 'Stob a''Choire Mheadhoin', 'Fort William to Loch Ericht', 1106),
    (47, 'Beinn Ghlas', 'Loch Rannoch to Loch Tay', 1103),
    (48, 'Mullach Fraoch-choire', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1102),
    (49, 'Beinn Eibhinn', 'Fort William to Loch Ericht', 1102),
    (50, 'Creise', 'Loch Leven to Connel Bridge and Glen Lochy', 1100),
    (51, 'Sgurr a''Mhaim', 'Fort William to Loch Ericht', 1099),
    (52, 'Sgurr Choinnich Mor', 'Fort William to Loch Ericht', 1094),
    (53, 'Sgurr nan Clach Geala', 'Loch Maree to Loch Broom and Garve', 1093),
    (54, 'Stob Ghabhar', 'Loch Leven to Connel Bridge and Glen Lochy', 1090),
    (55, 'Bynack More', 'The Cairngorms', 1090),
    (56, 'Beinn a''Chlachair', 'Fort William to Loch Ericht', 1087),
    (57, 'Beinn Dearg', 'Ullapool to the Moray Firth', 1084),
    (58, 'Sgurr a''Choire Ghlais', 'Kyle of Lochalsh to Inverness, North of Loch Mullardoch', 1083),
    (59, 'Schiehallion', 'Loch Rannoch to Loch Tay', 1083),
    (60, 'Beinn a''Chaorainn', 'The Cairngorms', 1082),
    (61, 'Beinn a''Chreachain', 'Loch Rannoch to Loch Tay', 1081),
    (62, 'Ben Starav', 'Loch Leven to Connel Bridge and Glen Lochy', 1078),
    (63, 'Beinn Heasgarnich [Beinn Sheasgarnaich]', 'Loch Rannoch to Loch Tay', 1078),
    (64, 'Beinn Dorain', 'Loch Rannoch to Loch Tay', 1076),
    (65, 'Stob Coire Sgreamhach', 'Loch Leven to Connel Bridge and Glen Lochy', 1072),
    (66, 'Beinn a''Ghlo - Braigh Coire Chruinn-bhalgain', 'Forest of Atholl to Braemar and Blairgowrie', 1070),
    (67, 'Meall Corranaich', 'Loch Rannoch to Loch Tay', 1069),
    (68, 'An Socach', 'Kyle of Lochalsh to Inverness, North of Loch Mullardoch', 1069),
    (69, 'Glas Maol', 'Braemar to Montrose', 1068),
    (70, 'Sgurr Fhuaran', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1067),
    (71, 'Cairn of Claise', 'Braemar to Montrose', 1064),
    (72, 'An Teallach - Bidein a''Ghlas Thuill', 'Loch Maree to Loch Broom and Garve', 1062),
    (73, 'An Teallach - Sgurr Fiona', 'Loch Maree to Loch Broom and Garve', 1060),
    (74, 'Na Gruagaichean', 'Fort William to Loch Ericht', 1056),
    (75, 'Liathach - Spidean a''Choire Leith', 'Loch Carron to Loch Maree', 1055),
    (76, 'Toll Creagach', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1054),
    (77, 'Stob Poite Coire Ardair', 'Spean Bridge to Elgin', 1054),
    (78, 'Sgurr a''Chaorachain', 'Kyle of Lochalsh to Inverness, North of Loch Mullardoch', 1053),
    (79, 'Glas Tulaichean', 'Forest of Atholl to Braemar and Blairgowrie', 1051),
    (80, 'Beinn a''Chaorainn', 'Spean Bridge to Elgin', 1050),
    (81, 'Sgurr Fhuar-thuill', 'Kyle of Lochalsh to Inverness, North of Loch Mullardoch', 1049),
    (82, 'Geal Charn', 'Fort William to Loch Ericht', 1049),
    (83, 'Creag Mhor', 'Loch Rannoch to Loch Tay', 1047),
    (84, 'Carn an t-Sagairt Mor', 'Braemar to Montrose', 1047),
    (85, 'Cruach Ardrain', 'Firth of Clyde to Strathtay', 1046),
    (86, 'Chno Dearg', 'Fort William to Loch Ericht', 1046),
    (87, 'Ben Wyvis - Glas Leathad Mor', 'Ullapool to the Moray Firth', 1046),
    (88, 'Beinn Iutharn Mhor', 'Forest of Atholl to Braemar and Blairgowrie', 1045),
    (89, 'Stob Coir'' an Albannaich', 'Loch Leven to Connel Bridge and Glen Lochy', 1044),
    (90, 'Meall nan Tarmachan', 'Loch Rannoch to Loch Tay', 1044),
    (91, 'Carn Mairg', 'Loch Rannoch to Loch Tay', 1042),
    (92, 'Sgurr na Ciche', 'Glen Shiel to Glenfinnan', 1040),
    (93, 'Meall Ghaordaidh', 'Loch Rannoch to Loch Tay', 1039),
    (94, 'Beinn Achaladair', 'Loch Rannoch to Loch Tay', 1038),
    (95, 'Carn a''Mhaim', 'The Cairngorms', 1037),
    (96, 'Sgurr a''Bhealaich Dheirg', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1036),
    (97, 'Gleouraich', 'Glen Shiel to Glenfinnan', 1035),
    (98, 'Carn Dearg', 'Fort William to Loch Ericht', 1034),
    (99, 'Beinn Fhada', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1032),
    (100, 'Am Bodach', 'Fort William to Loch Ericht', 1032),
    (101, 'Carn Gorm', 'Loch Rannoch to Loch Tay', 1029),
    (102, 'Carn an Righ', 'Forest of Atholl to Braemar and Blairgowrie', 1029),
    (103, 'Ben Oss', 'Firth of Clyde to Strathtay', 1029),
    (104, 'Sgurr na Ciste Duibhe', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1027),
    (105, 'Sgurr a''Mhaoraich', 'Glen Shiel to Glenfinnan', 1027),
    (106, 'Ben Challum [Beinn Challuim]', 'Loch Rannoch to Loch Tay', 1025),
    (107, 'Beinn a''Bheithir - Sgorr Dhearg', 'Loch Leven to Connel Bridge and Glen Lochy', 1024),
    (108, 'Liathach - Mullach an Rathain', 'Loch Carron to Loch Maree', 1023),
    (109, 'Aonach air Chrith', 'Glen Shiel to Glenfinnan', 1022),
    (110, 'Buachaille Etive Mor - Stob Dearg', 'Loch Leven to Connel Bridge and Glen Lochy', 1021),
    (111, 'Ladhar Bheinn', 'Glen Shiel to Glenfinnan', 1020),
    (112, 'Mullach Coire Mhic Fhearchair', 'Loch Maree to Loch Broom and Garve', 1019),
    (113, 'Mullach Clach a''Bhlair', 'The Cairngorms', 1019),
    (114, 'Carn an Tuirc', 'Braemar to Montrose', 1019),
    (115, 'Beinn Bheoil', 'Fort William to Loch Ericht', 1019),
    (116, 'Garbh Chioch Mhor', 'Glen Shiel to Glenfinnan', 1013),
    (117, 'Cairn Bannoch', 'Braemar to Montrose', 1012),
    (118, 'Beinn Ime', 'Firth of Clyde to Strathtay', 1011),
    (119, 'The Saddle', 'Glen Shiel to Glenfinnan', 1010),
    (120, 'Sgurr Eilde Mor', 'Fort William to Loch Ericht', 1010),
    (121, 'Sgurr an Doire Leathain', 'Glen Shiel to Glenfinnan', 1010),
    (122, 'Beinn Eighe - Ruadh-stac Mor', 'Loch Carron to Loch Maree', 1010),
    (123, 'Beinn Udlamain', 'Loch Ericht to Glen Tromie and Glen Garry', 1010),
    (124, 'Beinn Dearg', 'Forest of Atholl to Braemar and Blairgowrie', 1008),
    (125, 'Maoile Lunndaidh', 'Kyle of Lochalsh to Inverness, North of Loch Mullardoch', 1007),
    (126, 'Carn Liath', 'Spean Bridge to Elgin', 1006),
    (127, 'An Sgarsoch', 'Forest of Atholl to Braemar and Blairgowrie', 1006),
    (128, 'Beinn Fhionnlaidh', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1005),
    (129, 'The Devil''s Point', 'The Cairngorms', 1004),
    (130, 'Sgurr an Lochain', 'Glen Shiel to Glenfinnan', 1004),
    (131, 'Beinn an Dothaidh', 'Loch Rannoch to Loch Tay', 1004),
    (132, 'Sgurr Mor', 'Glen Shiel to Glenfinnan', 1003),
    (133, 'Sgurr na Carnach', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1002),
    (134, 'Sail Chaorainn [Sail Chaoruinn]', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1002),
    (135, 'Meall Greigh', 'Loch Rannoch to Loch Tay', 1001),
    (136, 'Beinn a''Bheithir - Sgorr Dhonuill', 'Loch Leven to Connel Bridge and Glen Lochy', 1001),
    (137, 'Aonach Meadhoin', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 1001),
    (138, 'Stob Ban', 'Fort William to Loch Ericht', 999),
    (139, 'Sgurr Choinnich', 'Kyle of Lochalsh to Inverness, North of Loch Mullardoch', 999),
    (140, 'Sgurr Breac', 'Loch Maree to Loch Broom and Garve', 999),
    (141, 'Stob Daimh [Stob Diamh]', 'Loch Leven to Connel Bridge and Glen Lochy', 998),
    (142, 'Broad Cairn', 'Braemar to Montrose', 998),
    (143, 'Ben More Assynt', 'The Far North', 998),
    (144, 'Glas Bheinn Mhor', 'Loch Leven to Connel Bridge and Glen Lochy', 997),
    (145, 'A''Chailleach', 'Loch Maree to Loch Broom and Garve', 997),
    (146, 'Spidean Mialach', 'Glen Shiel to Glenfinnan', 996),
    (147, 'An Caisteal', 'Firth of Clyde to Strathtay', 995),
    (148, 'Sgor na h-Ulaidh', 'Loch Leven to Connel Bridge and Glen Lochy', 994),
    (149, 'Carn an Fhidhleir [Carn Ealar]', 'Forest of Atholl to Braemar and Blairgowrie', 994),
    (150, 'Beinn Eighe - Spidean Coire nan Clach', 'Loch Carron to Loch Maree', 993),
    (151, 'Carn nan Gobhar', 'Kyle of Lochalsh to Inverness, North of Loch Mullardoch', 992),
    (152, 'Carn nan Gobhar', 'Kyle of Lochalsh to Inverness, North of Loch Mullardoch', 992),
    (153, 'Sgurr na Ruaidhe', 'Kyle of Lochalsh to Inverness, North of Loch Mullardoch', 992),
    (154, 'Sgurr Alasdair', 'Skye and Mull', 991),
    (155, 'Beinn Eunaich', 'Loch Leven to Connel Bridge and Glen Lochy', 989),
    (156, 'Sgairneach Mhor', 'Loch Ericht to Glen Tromie and Glen Garry', 989),
    (157, 'Druim Shionnach', 'Glen Shiel to Glenfinnan', 987),
    (158, 'Creag Leacach', 'Braemar to Montrose', 987),
    (159, 'Conival', 'The Far North', 987),
    (160, 'Sgurr Ban', 'Loch Maree to Loch Broom and Garve', 987),
    (161, 'Lurg Mhor', 'Kyle of Lochalsh to Inverness, North of Loch Mullardoch', 986),
    (162, 'Beinn Alligin - Sgurr Mhor', 'Loch Carron to Loch Maree', 986),
    (163, 'Gulvain [Gaor Bheinn]', 'Glen Shiel to Glenfinnan', 986),
    (164, 'Sgurr Dearg - Inaccessible Pinnacle', 'Skye and Mull', 985),
    (165, 'An Gearanach', 'Fort William to Loch Ericht', 982),
    (166, 'Ben Vorlich', 'Firth of Clyde to Strathtay', 982),
    (167, 'Slioch', 'Loch Maree to Loch Broom and Garve', 981),
    (168, 'Meall na Aighean', 'Loch Rannoch to Loch Tay', 981),
    (169, 'Maol Chinn-dearg', 'Glen Shiel to Glenfinnan', 981),
    (170, 'Mullach na Dheiragain', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 981),
    (171, 'Stob Coire a''Chairn', 'Fort William to Loch Ericht', 980),
    (172, 'Ciste Dhubh', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 979),
    (173, 'Beinn a''Chochuill', 'Loch Leven to Connel Bridge and Glen Lochy', 979),
    (174, 'Beinn Dubhchraig', 'Firth of Clyde to Strathtay', 978),
    (175, 'Stob Coire Sgriodain', 'Fort William to Loch Ericht', 978),
    (176, 'Meall nan Ceapraichean', 'Ullapool to the Moray Firth', 977),
    (177, 'Cona'' Mheall', 'Ullapool to the Moray Firth', 977),
    (178, 'Beinn a''Ghlo - Carn Liath', 'Forest of Atholl to Braemar and Blairgowrie', 975),
    (179, 'Carn a''Gheoidh', 'Forest of Atholl to Braemar and Blairgowrie', 975),
    (180, 'A''Mharconaich', 'Loch Ericht to Glen Tromie and Glen Garry', 975),
    (181, 'Stob Ban', 'Fort William to Loch Ericht', 975),
    (182, 'Beinn Sgritheall', 'Glen Shiel to Glenfinnan', 974),
    (183, 'Stuc a''Chroin', 'Firth of Clyde to Strathtay', 974),
    (184, 'Ben Lomond', 'Firth of Clyde to Strathtay', 973),
    (185, 'Sgurr a''Ghreadaidh', 'Skye and Mull', 972),
    (186, 'Meall Garbh', 'Loch Rannoch to Loch Tay', 968),
    (187, 'Aonach Eagach - Sgorr nam Fiannaidh', 'Loch Leven to Connel Bridge and Glen Lochy', 967),
    (188, 'A''Mhaighdean', 'Loch Maree to Loch Broom and Garve', 967),
    (189, 'Ben More', 'Skye and Mull', 966),
    (190, 'Sgurr na Banachdich', 'Skye and Mull', 965),
    (191, 'Sgurr nan Gillean', 'Skye and Mull', 964),
    (192, 'Sgurr Thuilm', 'Glen Shiel to Glenfinnan', 963),
    (193, 'Carn a''Chlamain', 'Forest of Atholl to Braemar and Blairgowrie', 963),
    (194, 'Ben Klibreck - Meall nan Con', 'The Far North', 962),
    (195, 'Sgorr Ruadh', 'Loch Carron to Loch Maree', 961),
    (196, 'Stuchd an Lochain [Stuc an Lochain]', 'Loch Rannoch to Loch Tay', 960),
    (197, 'Beinn nan Aighenan', 'Loch Leven to Connel Bridge and Glen Lochy', 960),
    (198, 'Meall Glas', 'Loch Rannoch to Loch Tay', 959),
    (199, 'Beinn Fhionnlaidh', 'Loch Leven to Connel Bridge and Glen Lochy', 959),
    (200, 'Tolmount', 'Braemar to Montrose', 958),
    (201, 'Buachaille Etive Beag - Stob Dubh', 'Loch Leven to Connel Bridge and Glen Lochy', 958),
    (202, 'Bruach na Frithe', 'Skye and Mull', 958),
    (203, 'Tom Buidhe', 'Braemar to Montrose', 957),
    (204, 'Carn Ghluasaid', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 957),
    (205, 'Sgurr nan Coireachan', 'Glen Shiel to Glenfinnan', 956),
    (206, 'Saileag', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 956),
    (207, 'Buachaille Etive Mor - Stob na Broige', 'Loch Leven to Connel Bridge and Glen Lochy', 956),
    (208, 'Sgor Gaibhre', 'Fort William to Loch Ericht', 955),
    (209, 'Am Faochagach', 'Ullapool to the Moray Firth', 954),
    (210, 'Beinn Liath Mhor Fannaich', 'Loch Maree to Loch Broom and Garve', 954),
    (211, 'Sgurr nan Coireachan', 'Glen Shiel to Glenfinnan', 953),
    (212, 'Aonach Eagach - Meall Dearg', 'Loch Leven to Connel Bridge and Glen Lochy', 953),
    (213, 'Beinn Mhanach', 'Loch Rannoch to Loch Tay', 953),
    (214, 'Meall Chuaich', 'Loch Ericht to Glen Tromie and Glen Garry', 951),
    (215, 'Meall Gorm', 'Loch Maree to Loch Broom and Garve', 949),
    (216, 'Sgurr Mhic Choinnich', 'Skye and Mull', 948),
    (217, 'Beinn Bhuidhe', 'Firth of Clyde to Strathtay', 948),
    (218, 'Driesh', 'Braemar to Montrose', 947),
    (219, 'Creag a''Mhaim', 'Glen Shiel to Glenfinnan', 947),
    (220, 'Meall Buidhe', 'Glen Shiel to Glenfinnan', 946),
    (221, 'Carn Bhac', 'Forest of Atholl to Braemar and Blairgowrie', 946),
    (222, 'Beinn Tulaichean', 'Firth of Clyde to Strathtay', 946),
    (223, 'Stob a''Choire Odhair', 'Loch Leven to Connel Bridge and Glen Lochy', 945),
    (224, 'Carn Dearg', 'Spean Bridge to Elgin', 945),
    (225, 'Bidein a''Choire Sheasgaich', 'Kyle of Lochalsh to Inverness, North of Loch Mullardoch', 945),
    (226, 'Sgurr na Sgine', 'Glen Shiel to Glenfinnan', 945),
    (227, 'Sgurr Dubh Mor', 'Skye and Mull', 944),
    (228, 'An Socach', 'Forest of Atholl to Braemar and Blairgowrie', 944),
    (229, 'Binnein Beag', 'Fort William to Loch Ericht', 943),
    (230, 'Ben Vorlich', 'Firth of Clyde to Strathtay', 943),
    (231, 'Carn na Caim', 'Loch Ericht to Glen Tromie and Glen Garry', 941),
    (232, 'Carn Dearg', 'Fort William to Loch Ericht', 941),
    (233, 'Beinn a''Chroin', 'Firth of Clyde to Strathtay', 940),
    (234, 'Mullach nan Coirean', 'Fort William to Loch Ericht', 939),
    (235, 'Mount Keen', 'Braemar to Montrose', 939),
    (236, 'Luinne Bheinn', 'Glen Shiel to Glenfinnan', 939),
    (237, 'A''Bhuidheanach Bheag', 'Loch Ericht to Glen Tromie and Glen Garry', 937),
    (238, 'Sron a''Choire Ghairbh', 'Glen Shiel to Glenfinnan', 937),
    (239, 'Beinn Tarsuinn', 'Loch Maree to Loch Broom and Garve', 937),
    (240, 'Beinn Sgulaird', 'Loch Leven to Connel Bridge and Glen Lochy', 937),
    (241, 'Beinn na Lap', 'Fort William to Loch Ericht', 936),
    (242, 'Meall a''Chrasgaidh', 'Loch Maree to Loch Broom and Garve', 934),
    (243, 'Am Basteir', 'Skye and Mull', 934),
    (244, 'The Cairnwell', 'Forest of Atholl to Braemar and Blairgowrie', 933),
    (245, 'Maol Chean-dearg', 'Loch Carron to Loch Maree', 933),
    (246, 'Fionn Bheinn', 'Loch Maree to Loch Broom and Garve', 933),
    (247, 'Beinn Chabhair', 'Firth of Clyde to Strathtay', 933),
    (248, 'Meall Buidhe', 'Loch Rannoch to Loch Tay', 932),
    (249, 'Ben Chonzie', 'Firth of Clyde to Strathtay', 931),
    (250, 'Beinn Bhreac', 'The Cairngorms', 931),
    (251, 'A''Chailleach', 'Spean Bridge to Elgin', 930),
    (252, 'Moruisg', 'Kyle of Lochalsh to Inverness, North of Loch Mullardoch', 928),
    (253, 'Meall nan Eun', 'Loch Leven to Connel Bridge and Glen Lochy', 928),
    (254, 'Mayar', 'Braemar to Montrose', 928),
    (255, 'Bla Bheinn [Blabheinn] [Blaven]', 'Skye and Mull', 928),
    (256, 'Ben Hope', 'The Far North', 927),
    (257, 'Beinn Narnain', 'Firth of Clyde to Strathtay', 927),
    (258, 'Seana Bhraigh', 'Ullapool to the Moray Firth', 926),
    (259, 'Meall a''Choire Leith', 'Loch Rannoch to Loch Tay', 926),
    (260, 'Geal Charn', 'Spean Bridge to Elgin', 926),
    (261, 'Beinn Liath Mhor', 'Loch Carron to Loch Maree', 926),
    (262, 'Eididh nan Clach Geala', 'Ullapool to the Moray Firth', 926),
    (263, 'Buachaille Etive Beag - Stob Coire Raineach', 'Loch Leven to Connel Bridge and Glen Lochy', 925),
    (264, 'Sgurr nan Eag', 'Skye and Mull', 924),
    (265, 'Creag Pitridh', 'Fort William to Loch Ericht', 924),
    (266, 'Sgurr nan Each', 'Loch Maree to Loch Broom and Garve', 923),
    (267, 'An Coileachan', 'Loch Maree to Loch Broom and Garve', 923),
    (268, 'Beinn Alligin - Tom na Gruagaich', 'Loch Carron to Loch Maree', 922),
    (269, 'Sgiath Chuil', 'Loch Rannoch to Loch Tay', 921),
    (270, 'An Socach', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 921),
    (271, 'Carn Sgulain', 'Spean Bridge to Elgin', 920),
    (272, 'Gairich', 'Glen Shiel to Glenfinnan', 919),
    (273, 'Sgurr a''Mhadaidh', 'Skye and Mull', 918),
    (274, 'Ruadh Stac Mor', 'Loch Maree to Loch Broom and Garve', 918),
    (275, 'Meall na Teanga', 'Glen Shiel to Glenfinnan', 918),
    (276, 'Creag nan Damh', 'Glen Shiel to Glenfinnan', 918),
    (277, 'A''Ghlas-bheinn', 'Loch Duich to Loch Ness, South of Loch Mullardoch', 918),
    (278, 'Geal-charn', 'Loch Ericht to Glen Tromie and Glen Garry', 917),
    (279, 'Carn Aosda', 'Forest of Atholl to Braemar and Blairgowrie', 917),
    (280, 'Beinn a''Chleibh', 'Firth of Clyde to Strathtay', 916),
    (281, 'Ben Vane', 'Firth of Clyde to Strathtay', 915),
    (282, 'Beinn Teallach', 'Spean Bridge to Elgin', 915);

INSERT INTO climbed_munro (id, climb_date, munro_id)
VALUES
    (1, '2017/12/24', 254),
    (2, '2017/12/24', 218),
    (3, '2019/08/10', 190),
    (4, '2021/04/24', 235),
    (5, '2024/10/29', 189),
    (6, '2025/07/12', 279),
    (7, '2025/07/12', 179),
    (8, '2025/07/12', 244),
    (9, '2025/07/12', 69),
    (10, '2025/07/12', 158);